### ISSUE TITLE
ImportError: No module named 'lib'

### ISSUE THREAD

**Issue by ngautam0** [rfguri/perceptron#1]
**Works fine in Python version 2.7.12**

**The Error is for Python 3.5.2**

**While Importing the perceptron module, I am getting the following error : -**

` ImportError                               Traceback (most recent call last)`
` <ipython-input-2-f4fe3356ce31> in <module>()`
`----> 1 from perceptron import mlp`
`      2 `
`      3 def perceptron():`
`      4     n = mlp.Net()`
`      5 `

`/usr/local/lib/python3.5/dist-packages/perceptron/mlp.py in <module>()`
`----> 1 from lib import trainer`
`      2 `
`      3 class Net:`
`      4     def __init__(self,mode='',dbname='nn.db'):`
`      5         self.trainer = trainer.Trainer(mode,dbname)`

`ImportError: No module named 'lib'`

**The following import works fine :** 
`import perceptron as pc`

**where as the following throws error :** 
`from lib import trainer`

`ImportError                               Traceback (most recent call last)`
`<ipython-input-15-f93226cf3c23> in <module>()`
`----> 1 from lib import trainer`

`ImportError: No module named 'lib'`

**Comment by ArtificialZeng** [comment]
ImportError: cannot import name 'trainer'

**Comment by Tubaleviao** [comment]
Same here
